const frases = [
  { imagem: "/../img/falar.png", frase: "MEU NOME É X", categoria: "falar" },
  { imagem: "/../img/idade.png", frase: "EU TENHO X ANOS", categoria: "falar" },
  { imagem: "../img/tudo-bem.png", frase: "TUDO BEM?", categoria: "falar" },
  { imagem: "../img/sim.png", frase: "SIM", categoria: "falar" },
  { imagem: "../img/não.png", frase: "NÃO", categoria: "falar" },
  { imagem: "../img/por-favor.png", frase: "POR FAVOR", categoria: "falar" },
  { imagem: "../img/obrigado.png", frase: "OBRIGADO", categoria: "falar" },
  { imagem: "../img/nao-entendi.png", frase: "NÃO ENTENDI", categoria: "falar" },

  { imagem: "../img/podxe-me-ajudar.png", frase: "PODE ME AJUDAR?", categoria: "ajuda" },
  { imagem: "../img/como-faco.png", frase: "COMO FAÇO ISSO?", categoria: "ajuda" },
  { imagem: "../img/preciso-de-ajuda.png", frase: "PRECISO DE AJUDA", categoria: "ajuda" },
  { imagem: "../img/nao-estou-conseguindo.png", frase: "NÃO ESTOU CONSEGUINDO", categoria: "ajuda" },
  { imagem: "../img/repetir.png", frase: "PODE REPETIR?", categoria: "ajuda" },
  { imagem: "../img/como-faz.png", frase: "ME MOSTRA COMO FAZ", categoria: "ajuda" },
  { imagem: "../img/esta-dificil.png", frase: "ESTÁ DIFICIL", categoria: "ajuda" },
  { imagem: "../img/nao-sei.png", frase: "NÃO SEI", categoria: "ajuda" },

  { imagem: "../img/mae.png", frase: "QUERO FALAR COM A MINHA MÃE", categoria: "pessoas" },
  { imagem: "../img/pai.png", frase: "QUERO FALAR COM O MEU PAI", categoria: "pessoas" },
  { imagem: "../img/amigo.png", frase: "QUERO FALAR COM O MEU AMIGO", categoria: "pessoas" },
  { imagem: "../img/mensagem.png", frase: "QUERO MANDAR UMA MENSAGEM", categoria: "pessoas" },
  { imagem: "../img/saudade.png", frase: "ESTOU COM SAUDADE", categoria: "pessoas" },
  { imagem: "../img/posso-ligar.png", frase: "POSSO TE LIGAR?", categoria: "pessoas" },
  { imagem: "../img/gosto-de-voce.png", frase: "EU GOSTO DE VOCÊ", categoria: "pessoas" },
  { imagem: "../img/te-amo.png", frase: "EU TE AMO", categoria: "pessoas" },

  { imagem: "../img/feliz.png", frase: "ESTOU FELIZ", categoria: "sentimentos" },
  { imagem: "../img/triste.png", frase: "ESTOU TRISTE", categoria: "sentimentos" },
  { imagem: "../img/raiva.png", frase: "ESTOU COM RAIVA", categoria: "sentimentos" },
  { imagem: "../img/estou-com-medo.png", frase: "ESTOU COM MEDO", categoria: "sentimentos" },
  { imagem: "../img/cansado.png", frase: "ESTOU CANSADO", categoria: "sentimentos" },
  { imagem: "../img/animado.png", frase: "ESTOU ANIMADO", categoria: "sentimentos" },
  { imagem: "../img/nervoso.png", frase: "ESTOU NERVOSO", categoria: "sentimentos" },
  { imagem: "../img/vergonha.png", frase: "ESTOU COM VERGONHA", categoria: "sentimentos" },

  { imagem: "../img/acordar.png", frase: "PRECISO ACORDAR CEDO", categoria: "rotina" },
  { imagem: "../img/escola.png", frase: "TENHO QUE IR À ESCOLA", categoria: "rotina" },
  { imagem: "../img/almoço.png", frase: "É HORA DO ALMOÇO", categoria: "rotina" },
  { imagem: "../img/remedio.png", frase: "TENHO QUE TOMAR REMÉDIO", categoria: "rotina" },
  { imagem: "../img/tomando-banho.png", frase: "É HORA DO BANHO", categoria: "rotina" },
  { imagem: "../img/dormir.png", frase: "PRECISO DORMIR CEDO", categoria: "rotina" },
  { imagem: "../img/hospital.png", frase: "TENHO UMA CONSULTA HOJE", categoria: "rotina" },
  { imagem: "../img/tarefa.png", frase: "JÁ TERMINEI MINHA TAREFA", categoria: "rotina" },

  { imagem: "../img/casa.png", frase: "QUERO IR PARA CASA", categoria: "lugares" },
  { imagem: "../img/escola.png", frase: "QUERO IR PARA A ESCOLA", categoria: "lugares" },
  { imagem: "../img/parque.png", frase: "QUERO IR AO PARQUE", categoria: "lugares" },
  { imagem: "../img/hospital.png", frase: "QUERO IR AO HOSPITAL", categoria: "lugares" },
  { imagem: "../img/mercado.png", frase: "QUERO IR AO MERCADO", categoria: "lugares" },
  { imagem: "../img/caminhar.png", frase: "QUERO SAIR PARA PASSEAR", categoria: "lugares" },
  { imagem: "../img/igreja.png", frase: "QUERO IR À IGREJA", categoria: "lugares" },
  { imagem: "../img/mapa.png", frase: "ONDE ESTAMOS AGORA?", categoria: "lugares" },

  { imagem: "../img/com-fome.png", frase: "ESTOU COM FOME", categoria: "comer-beber" },
  { imagem: "../img/desidratacao.png", frase: "ESTOU COM SEDE", categoria: "comer-beber" },
  { imagem: "../img/almoço.png", frase: "QUERO COMER", categoria: "comer-beber" },
  { imagem: "../img/sede.png", frase: "QUERO BEBER", categoria: "comer-beber" },
  { imagem: "../img/comida-ruim.png", frase: "NÃO GOSTEI DA COMIDA", categoria: "comer-beber" },
  { imagem: "../img/.png", frase: "QUERO MAIS, POR FAVOR", categoria: "comer-beber" },
  { imagem: "../img/comi-suficiente.png", frase: "JÁ COMI O SUFICIENTE", categoria: "comer-beber" },
  { imagem: "../img/sobremesa.png", frase: "QUERO UMA SOBREMESA", categoria: "comer-beber" },

  { imagem: "../img/.png", frase: "ESTOU COM DOR", categoria: "saude" },
  { imagem: "../img/.png", frase: "ESTOU COM FEBRE", categoria: "saude" },
  { imagem: "../img/.png", frase: "ESTOU ENJOADO", categoria: "saude" },
  { imagem: "../img/.png", frase: "PRECISO IR AO MÉDICO", categoria: "saude" },
  { imagem: "../img/.png", frase: "PRECISO TOMAR REMÉDIO", categoria: "saude" },
  { imagem: "../img/.png", frase: "ESTOU ME SENTINDO BEM", categoria: "saude" },
  { imagem: "../img/.png", frase: "ESTOU ME SENTINDO MAL", categoria: "saude" },
  { imagem: "../img/.png", frase: "TENHO ALERGIA", categoria: "saude" },

  { imagem: "../img/.png", frase: "QUERO BRINCAR", categoria: "lazer" },
  { imagem: "../img/.png", frase: "QUERO JOGAR BOLA", categoria: "lazer" },
  { imagem: "../img/.png", frase: "QUERO VER TV", categoria: "lazer" },
  { imagem: "../img/.png", frase: "QUERO OUVIR MÚSICA", categoria: "lazer" },
  { imagem: "../img/.png", frase: "QUERO DESENHAR", categoria: "lazer" },
  { imagem: "../img/.png", frase: "QUERO SAIR COM MEUS AMIGOS", categoria: "lazer" },
  { imagem: "../img/.png", frase: "QUERO PASSEAR", categoria: "lazer" },
  { imagem: "../img/.png", frase: "QUERO DESCANSAR", categoria: "lazer" },

  { imagem: "../img/.png", frase: "PRECISO ESTUDAR", categoria: "estudar" },
  { imagem: "../img/.png", frase: "NÃO ENTENDI A ATIVIDADE", categoria: "estudar" },
  { imagem: "../img/.png", frase: "POSSO FAZER DE NOVO A ATIVIDADE?", categoria: "estudar" },
  { imagem: "../img/.png", frase: "JÁ TERMINEI O EXERCÍCIO", categoria: "estudar" },
  { imagem: "../img/.png", frase: "PRECISO DE AJUDA COM A ATIVIDADE", categoria: "estudar" },
  { imagem: "../img/.png", frase: "POSSO USAR O COMPUTADOR?", categoria: "estudar" },
  { imagem: "../img/.png", frase: "TENHO PROVA HOJE", categoria: "estudar" },
  { imagem: "../img/.png", frase: "ESQUECI MEU MATERIAL", categoria: "estudar" },

  { imagem: "../img/.png", frase: "PRECISO IR AO BANHEIRO", categoria: "necessidades" },
  { imagem: "../img/.png", frase: "ESTOU COM FRIO", categoria: "necessidades" },
  { imagem: "../img/.png", frase: "ESTOU COM CALOR", categoria: "necessidades" },
  { imagem: "../img/.png", frase: "ESTOU COM SONO", categoria: "necessidades" },
  { imagem: "../img/.png", frase: "PRECISO DESCANSAR", categoria: "necessidades" },
  { imagem: "../img/.png", frase: "QUERO TOMAR BANHO", categoria: "necessidades" },
  { imagem: "../img/.png", frase: "QUERO TROCAR DE ROUPA", categoria: "necessidades" },
  { imagem: "../img/.png", frase: "QUERO PRIVACIDADE", categoria: "necessidades" },

  { imagem: "../img/.png", frase: "ESTOU INDO TRABALHAR", categoria: "trabalho" },
  { imagem: "../img/.png", frase: "JA TERMINEI MINHA TAREFA", categoria: "trabalho" },
  { imagem: "../img/.png", frase: "PRECISO DE AJUDA COM O SERVIÇO", categoria: "trabalho" },
  { imagem: "../img/.png", frase: "POSSO FAZER UMA PAUSA?", categoria: "trabalho" },
  { imagem: "../img/.png", frase: "TENHO REUNIÃO HOJE", categoria: "trabalho" },
  { imagem: "../img/.png", frase: "ESTOU SAINDO DO TRABALHO", categoria: "trabalho" },
  { imagem: "../img/.png", frase: "COM O QUE POSSO AJUDAR?", categoria: "trabalho" },
  { imagem: "../img/.png", frase: "QUERO TE MOSTRAR O QUE EU FI", categoria: "trabalho" },
];